---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - name: db
        image: postgres:9.6.2
        ports:
        - containerPort: 5432
        env:
        - name: TZ
          value: "Europe/Zurich"
        - name: POSTGRES_DB
          value: reana
        {{- if .Values.debug.enabled }}
        - name: POSTGRES_USER
          value: reana
        - name: POSTGRES_PASSWORD
          value: reana
        {{- else }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        {{- end }}
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.volume_paths.db_persistence_path }}
