---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-workflow-controller
spec:
  type: "NodePort"
  ports:
  - port: 80
    targetPort: 5000
    name: "http"
    protocol: TCP
  selector:
      app: {{ .Release.Name }}-workflow-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-workflow-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-workflow-controller
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-workflow-controller
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: rest-api
        image: {{ .Values.components.reana_workflow_controller.image }}
        imagePullPolicy: {{ .Values.components.reana_workflow_controller.imagePullPolicy }}
        ports:
        - containerPort: 5000
          name: http
        {{- if .Values.debug.enabled }}
        command: ["/bin/sh","-c"]
        args: ["flask run --host=0.0.0.0"]
        tty: true
        stdin: true
        {{- end }}
        volumeMounts:
          {{- if .Values.debug.enabled }}
          - mountPath: /code
            name: reana-code
          {{- end }}
          - mountPath: {{ .Values.volume_paths.shared_volume_path }}
            name: reana-shared-volume
        env:
        {{- range $key, $value := .Values.db_env_config }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        {{- range $key, $value := .Values.components.reana_workflow_controller.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: K8S_REANA_SERVICE_ACCOUNT_NAME
          value: {{ .Values.serviceAccount.name }}
        {{- if .Values.reana_url }}
        - name: REANA_URL
          value: {{ .Values.reana_url }}
        {{- end }}
        {{- if .Values.eos.enabled }}
        - name: K8S_CERN_EOS_AVAILABLE
          value: "True"
        {{ end }}
        {{- if .Values.cephfs.enabled }}
        - name: REANA_STORAGE_BACKEND
          value: "cephfs"
        {{ end }}
        {{- if not .Values.debug.enabled }}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        - name: REANA_GITLAB_HOST
          valueFrom:
            secretKeyRef:
              name: reana-cern-gitlab-secrets
              key: REANA_GITLAB_HOST
        {{ end }}
      - name: job-status-consumer
        image: {{ .Values.components.reana_workflow_controller.image }}
        imagePullPolicy: {{ .Values.components.reana_workflow_controller.imagePullPolicy }}
        command: ["flask", "consume-job-queue"]
        volumeMounts:
          {{- if .Values.debug.enabled }}
          - mountPath: /code
            name: reana-code
          {{- end }}
          - mountPath: {{ .Values.volume_paths.shared_volume_path }}
            name: reana-shared-volume
        env:
        {{- range $key, $value := .Values.db_env_config }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
        {{- range $key, $value := .Values.components.reana_workflow_controller.environment }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- if .Values.reana_url }}
        - name: REANA_URL
          value: {{ .Values.reana_url }}
        {{- end }}
        {{- if not .Values.debug.enabled }}
        - name: REANA_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: user
        - name: REANA_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reana-db-secrets
              key: password
        {{ end }}
      volumes:
      - name: reana-shared-volume
        {{- if .Values.cephfs.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-cephfs
          readOnly: false
        {{- else }}
        hostPath:
          path: {{ .Values.volume_paths.root_path }}
        {{- end }}
      {{- if .Values.debug.enabled }}
      - name: reana-code
        hostPath:
          path: /code/reana-workflow-controller
      {{- end }}
