---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manila-csicephfs-share
provisioner: manila-provisioner
parameters:
  type: "Geneva CephFS Testing"
  zones: nova
  osSecretName: ceph-secret
  osSecretNamespace: default
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: csi-cephfsplugin
  os-shareID: #
  os-shareAccessID: #
  # monitors: {{ CEPHFS_MONITORS|join(',') }}
  provisionVolume: "false"
  rootPath: {{ROOT_PATH}}
reclaimPolicy: Delete
